import {
    collection,
    doc,
    getDoc,
    getDocs,
    query,
    serverTimestamp,
    setDoc,
    where,
    type Firestore
} from 'firebase/firestore'

export const GROUP_INTERVENTION_DELIVERIES_COLLECTION = 'groupInterventionDeliveries'
export const GROUP_INTERVENTION_DELIVERY_SCHEMA_VERSION = 1

export type GroupInterventionDelivery = {
    id: string
    groupKey: string
    programId?: string | null
    departmentId?: string | null
    interventionId?: string | null
    interventionTitle?: string | null
    subInterventionId?: string | null
    subInterventionTitle?: string | null
    assigneeId?: string | null
    assigneeEmail?: string | null
    assigneeName?: string | null
    progress: number
    deliveryStatus: 'not_started' | 'in_progress' | 'completed'
    evidence: Array<Record<string, any>>
    progressUpdates: Array<Record<string, any>>
    coverageHistory?: Array<Record<string, any>>
    latestCoverage?: Record<string, any> | null
    sessionsCompleted?: number
    plannedSessions?: number
    sourceAssignmentIds: string[]
    completedAt?: any
    createdAt?: any
    updatedAt?: any
}

const clean = (value: unknown) => String(value || '').trim()
const clamp = (value: unknown) => Math.max(0, Math.min(100, Number(value) || 0))

// Firestore rejects undefined anywhere in an object/array. Group rows are
// assembled from older assignment records, so strip those values at the
// service boundary instead of letting one legacy member abort the save.
const withoutUndefined = (value: any): any => {
    if (Array.isArray(value)) return value.filter(item => item !== undefined).map(withoutUndefined)
    if (!value || typeof value !== 'object') return value
    return Object.fromEntries(
        Object.entries(value)
            .filter(([, nested]) => nested !== undefined)
            .map(([key, nested]) => [key, withoutUndefined(nested)])
    )
}

// Group keys are generated by this system and are safe document identifiers.
// Encoding also protects any older imported key that contains a slash.
export const groupDeliveryId = (groupKey: string) => encodeURIComponent(clean(groupKey))

export const groupDeliveryRef = (firestore: Firestore, groupKey: string) =>
    doc(firestore, GROUP_INTERVENTION_DELIVERIES_COLLECTION, groupDeliveryId(groupKey))

export const progressFromGroupDelivery = (delivery?: Partial<GroupInterventionDelivery> | null) =>
    clamp(delivery?.progress)

export async function getGroupDelivery(
    firestore: Firestore,
    groupKey: string
): Promise<GroupInterventionDelivery | null> {
    const snapshot = await getDoc(groupDeliveryRef(firestore, groupKey))
    return snapshot.exists()
        ? { ...(snapshot.data() as GroupInterventionDelivery), id: snapshot.id }
        : null
}

export const groupDeliveryWrite = (
    input: Omit<GroupInterventionDelivery, 'id' | 'createdAt' | 'updatedAt' | 'schemaVersion'>
) => ({
    ...withoutUndefined({
        ...input,
        groupKey: clean(input.groupKey),
        progress: clamp(input.progress),
        schemaVersion: GROUP_INTERVENTION_DELIVERY_SCHEMA_VERSION
    }),
    updatedAt: serverTimestamp(),
    createdAt: serverTimestamp()
})

export async function loadGroupDeliveriesForAssignee(
    firestore: Firestore,
    assigneeId: string,
    assigneeEmail?: string | null
): Promise<Record<string, GroupInterventionDelivery>> {
    const deliveries = collection(firestore, GROUP_INTERVENTION_DELIVERIES_COLLECTION)
    const snapshots = await Promise.allSettled([
        assigneeId ? getDocs(query(deliveries, where('assigneeId', '==', assigneeId))) : Promise.resolve(null),
        assigneeEmail ? getDocs(query(deliveries, where('assigneeEmail', '==', assigneeEmail))) : Promise.resolve(null)
    ])

    const byKey: Record<string, GroupInterventionDelivery> = {}
    snapshots.forEach(result => {
        if (result.status !== 'fulfilled' || !result.value) return
        result.value.docs.forEach(snapshot => {
            const data = snapshot.data() as GroupInterventionDelivery
            if (clean(data.groupKey)) byKey[data.groupKey] = { ...data, id: snapshot.id }
        })
    })
    return byKey
}

export async function saveGroupDelivery(
    firestore: Firestore,
    input: Omit<GroupInterventionDelivery, 'id' | 'createdAt' | 'updatedAt' | 'schemaVersion'>
) {
    const groupKey = clean(input.groupKey)
    if (!groupKey) throw new Error('A group key is required for shared delivery.')

    await setDoc(groupDeliveryRef(firestore, groupKey), groupDeliveryWrite(input), { merge: true })
}
