const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const ts = require('typescript');
function load(file, overrides={}) {
 const module={exports:{}};
 const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;
 vm.runInNewContext(code,{module,exports:module.exports,require:name=>overrides[name]||require(name),URL,Date,console,fetch:async()=>({ok:true,json:async()=>({candidates:[{content:{parts:[{text:'Explain the reasoning behind your answer.'}]}}]})})},{filename:file});
 return module.exports;
}
const domain=load('functions/src/courseDomain.ts');
const question=(id,answer=0)=>({id,text:`Question ${id}`,options:['Yes','No'],answer,feedback:'Review the concept.'});
const item=(id,kind='lesson')=>({id,moduleId:'m',kind,title:id,objective:'Apply the concept',content:'Read the brief',minutes:10,required:true,passMark:70,questions:kind==='quiz'?[question('q')]:[],welcome:'Welcome',attempts:2,scorePolicy:'best',timeLimit:0,rubric:'Accurate response',submissionType:'text',knowledge:'Approved facts',reflectionPrompt:'What did you learn?',minTurns:2});
const course=(items=[item('lesson'),item('quiz','quiz'),item('assignment','assignment')])=>({title:'Business basics',description:'Learn the basics',level:'Beginner',modules:[{id:'m',title:'Basics'}],items,sequential:true});
function setup(draft=course()) {
 const state=new Map([['users/author',{role:'operations'}],['academyDrafts/c',{...draft,id:'c',owner:'author',revision:1,publishedRevision:0,updatedAt:'saved'}]]);
 const clone=x=>x===undefined?undefined:JSON.parse(JSON.stringify(x));
 const snap=(path,map=state)=>({id:path.split('/').pop(),exists:map.has(path),data:()=>clone(map.get(path))});
 let chain=Promise.resolve();
 const db={doc:path=>({path,get:async()=>snap(path)}),runTransaction:callback=>{
  const next=chain.then(async()=>{const working=new Map([...state].map(([key,value])=>[key,clone(value)]));const result=await callback({get:async ref=>snap(ref.path,working),set:(ref,value)=>working.set(ref.path,clone(value)),create:(ref,value)=>{assert.ok(!working.has(ref.path));working.set(ref.path,clone(value));},update:(ref,value)=>working.set(ref.path,{...working.get(ref.path),...clone(value)})});state.clear();working.forEach((v,k)=>state.set(k,v));return result;});chain=next.catch(()=>{});return next;
 }};
 class HttpsError extends Error {constructor(code,message){super(message);this.code=code;}}
 const api=load('functions/src/academy.ts',{'./firebase':{db},'./courseDomain':domain,'firebase-functions/v2/https':{onCall:(_options,handler)=>handler,HttpsError},'firebase-functions/params':{defineSecret:()=>({value:()=> 'test'}),defineString:()=>({value:()=> 'test-model'})}});
 const call=(action,data={},uid='learner')=>api.academyAction({auth:{uid},data:{action,...data}});
 const publish=()=>call('publish',{courseId:'c',updatedAt:'saved'},'author');
 const enrol=()=>call('enroll',{courseId:'c'});
 const act=(action,itemId,extra={},uid='learner')=>call(action,{enrollmentId:'learner_c',itemId,...extra},uid);
 return {state,call,publish,enrol,act,api};
}
test('20-question validation points to the missing correct answer',()=>{const quiz=item('quiz','quiz');quiz.questions=Array.from({length:20},(_,n)=>question(`q${n}`));quiz.questions[17].answer=-1;const errors=domain.validateCourse(course([quiz]));assert.equal(errors.length,1);assert.equal(errors[0].questionId,'q17');});
test('normalization preserves legacy items and module order',()=>{const legacy=domain.normalizeCourse({...course(),modules:undefined});assert.equal(legacy.items[0].moduleId,'module-1');const c=course([item('one'),{...item('two'),moduleId:'n'}]);c.modules.unshift({id:'n',title:'First'});assert.equal(domain.orderedItems(c)[0].id,'two');});
test('public course removes answer keys, feedback and coach knowledge',()=>{const c=course([item('quiz','quiz'),item('coach','interactive')]);const output=domain.publicCourse(c);assert.equal(output.items[0].questions[0].answer,-1);assert.equal(output.items[0].questions[0].feedback,'');assert.equal(output.items[1].knowledge,'');assert.equal(c.items[0].questions[0].answer,0);});
test('publication validates owner and pins immutable enrolled versions',async()=>{const s=setup();await assert.rejects(s.call('publish',{courseId:'c',updatedAt:'saved'}),/author/);await s.publish();const first=await s.enrol();s.state.get('academyDrafts/c').title='Revised';await s.publish();assert.equal((await s.enrol()).revision,first.revision);assert.equal(s.state.get('academyVersions/c_1').title,'Business basics');assert.equal(s.state.get('academyVersions/c_2').title,'Revised');});
test('publishing rejects stale review and incomplete answer keys',async()=>{const s=setup();await assert.rejects(s.call('publish',{courseId:'c',updatedAt:'old'},'author'),/changed/);s.state.get('academyDrafts/c').items[1].questions[0].answer=-1;await assert.rejects(s.publish(),/correct answer/);assert.ok(!s.state.has('academyCatalog/c'));});
test('sequential gating rejects learner skipping required lesson',async()=>{const s=setup();await s.publish();await s.enrol();await assert.rejects(s.act('start','quiz'),/previous/);await assert.rejects(s.act('submit','lesson'),/Confirm/);await s.act('submit','lesson',{acknowledged:true});const started=await s.act('start','quiz');assert.equal(started.items.quiz.attempts,1);});
test('concurrent start is idempotent and submit cannot score twice',async()=>{const s=setup(course([item('quiz','quiz')]));await s.publish();await s.enrol();const [a,b]=await Promise.all([s.act('start','quiz'),s.act('start','quiz')]);assert.equal(a.items.quiz.attemptId,b.items.quiz.attemptId);const result=await s.act('submit','quiz',{attemptId:a.items.quiz.attemptId,answers:{q:0}});assert.equal(result.items.quiz.score,100);assert.equal(result.items.quiz.status,'completed');await assert.rejects(s.act('submit','quiz',{attemptId:a.items.quiz.attemptId,answers:{q:1}}),/already/);});
test('best score is retained and attempt limit is enforced',async()=>{const s=setup(course([item('quiz','quiz')]));await s.publish();await s.enrol();let e=await s.act('start','quiz');await s.act('submit','quiz',{attemptId:e.items.quiz.attemptId,answers:{q:0}});e=await s.act('start','quiz');e=await s.act('submit','quiz',{attemptId:e.items.quiz.attemptId,answers:{q:1}});assert.equal(e.items.quiz.score,100);await assert.rejects(s.act('start','quiz'),/No attempts/);});
test('timed attempts permit partial submission after expiration',async()=>{const s=setup(course([{...item('quiz','quiz'),timeLimit:1}]));await s.publish();await s.enrol();const e=await s.act('start','quiz');await assert.rejects(s.act('submit','quiz',{attemptId:e.items.quiz.attemptId,answers:{}}),/every question/);s.state.get('academyEnrollments/learner_c').items.quiz.startedAt=Date.now()-120000;const result=await s.act('submit','quiz',{attemptId:e.items.quiz.attemptId,answers:{}});assert.equal(result.items.quiz.score,0);assert.match(result.items.quiz.feedback,/Time limit/);});
test('assignment requires author review and supports changes then resubmission',async()=>{const s=setup(course([item('assignment','assignment')]));await s.publish();await s.enrol();await assert.rejects(s.act('submit','assignment',{text:''}),/required submission/);await s.act('submit','assignment',{text:'My work'});await assert.rejects(s.act('review','assignment',{decision:'approve'}),/cannot/);await s.act('review','assignment',{decision:'revise',feedback:'Explain more'},'author');await s.act('submit','assignment',{text:'Revised work'});const result=await s.act('review','assignment',{decision:'approve'},'author');assert.equal(result.items.assignment.status,'completed');});
test('learners cannot mutate other enrollments',async()=>{const s=setup();await s.publish();await s.enrol();await assert.rejects(s.act('submit','lesson',{acknowledged:true},'intruder'),/cannot/);});
test('AI completion requires exchanges and a reflection',async()=>{const s=setup(course([item('coach','interactive')]));await s.publish();await s.enrol();await assert.rejects(s.act('submit','coach',{text:'Reflection'}),/exchanges/);for(let n=0;n<2;n++)await s.api.academyCoach({auth:{uid:'learner'},data:{enrollmentId:'learner_c',itemId:'coach',text:'Help me understand'}});await assert.rejects(s.act('submit','coach',{text:''}),/reflection/);const result=await s.act('submit','coach',{text:'I can now explain the concept'});assert.equal(result.items.coach.status,'completed');});
test('expired assessments ignore answers supplied after deadline',async()=>{const s=setup(course([{...item('quiz','quiz'),timeLimit:1}]));await s.publish();await s.enrol();const e=await s.act('start','quiz');await s.act('draft','quiz',{attemptId:e.items.quiz.attemptId,answers:{q:1}});s.state.get('academyEnrollments/learner_c').items.quiz.startedAt=Date.now()-120000;await assert.rejects(s.act('draft','quiz',{attemptId:e.items.quiz.attemptId,answers:{q:0}}),/Time is up/);const result=await s.act('submit','quiz',{attemptId:e.items.quiz.attemptId,answers:{q:0}});assert.equal(result.items.quiz.score,0);});
test('latest-score policy replaces the prior passing score',async()=>{const s=setup(course([{...item('quiz','quiz'),scorePolicy:'latest'}]));await s.publish();await s.enrol();let e=await s.act('start','quiz');await s.act('submit','quiz',{attemptId:e.items.quiz.attemptId,answers:{q:0}});e=await s.act('start','quiz');e=await s.act('submit','quiz',{attemptId:e.items.quiz.attemptId,answers:{q:1}});assert.equal(e.items.quiz.score,0);assert.notEqual(e.items.quiz.status,'completed');});
test('question drafts persist for resume and reject old attempt writes',async()=>{const s=setup(course([item('quiz','quiz')]));await s.publish();await s.enrol();const e=await s.act('start','quiz');await assert.rejects(s.act('draft','quiz',{attemptId:'old',answers:{q:0}}),/no longer active/);await s.act('draft','quiz',{attemptId:e.items.quiz.attemptId,answers:{q:1}});assert.equal((await s.enrol()).items.quiz.answers.q,1);});
test('optional lessons do not block later required items',()=>{const c=course([{...item('optional'),required:false},item('required')]);assert.equal(domain.canOpenItem(c,{},'required'),true);assert.equal(domain.canOpenItem(c,{},'missing'),false);});
test('unapproved assignments do not count as complete or unlock next item',async()=>{const s=setup(course([item('assignment','assignment'),item('next')]));await s.publish();await s.enrol();const e=await s.act('submit','assignment',{text:'Work'});assert.equal(e.items.assignment.status,'submitted');await assert.rejects(s.act('submit','next',{acknowledged:true}),/previous/);});
test('assessments do not require a learning objective but lessons do',()=>{const quiz={...item('quiz','quiz'),objective:''};const test={...item('test','test'),objective:'',questions:[question('t')]};const lesson={...item('lesson'),objective:''};const messages=domain.validateCourse(course([quiz,test,lesson])).map(i=>i.message);assert.equal(JSON.stringify(messages),JSON.stringify(['lesson: Add a learning objective.']));});
test('tests hide answer explanations unless the author enables them',async()=>{const hidden={...item('test','test'),questions:[question('t')]};const s=setup(course([hidden]));await s.publish();await s.enrol();let e=await s.act('start','test');e=await s.act('submit','test',{attemptId:e.items.test.attemptId,answers:{t:1}});assert.doesNotMatch(e.items.test.feedback,/Review the concept/);const shown={...item('test','test'),questions:[question('t')],showFeedback:true};const s2=setup(course([shown]));await s2.publish();await s2.enrol();e=await s2.act('start','test');e=await s2.act('submit','test',{attemptId:e.items.test.attemptId,answers:{t:1}});assert.match(e.items.test.feedback,/Review the concept/);const q=setup(course([item('quiz','quiz')]));await q.publish();await q.enrol();e=await q.act('start','quiz');e=await q.act('submit','quiz',{attemptId:e.items.quiz.attemptId,answers:{q:1}});assert.match(e.items.quiz.feedback,/Review the concept/);});
test('deleting a course blocks new enrolments and restoration makes it available again',async()=>{const s=setup();await s.publish();await s.enrol();await s.call('deleteCourse',{courseId:'c'},'author');assert.ok(s.state.get('academyDrafts/c').deletedAt);assert.equal(s.state.get('academyCatalog/c').deletedAt,s.state.get('academyDrafts/c').deletedAt);await assert.rejects(s.call('enroll',{courseId:'c'},'newLearner'),/not available/);assert.equal((await s.enrol()).id,'learner_c');await s.call('restoreCourse',{courseId:'c'},'author');assert.equal(s.state.get('academyDrafts/c').deletedAt,null);assert.equal(s.state.get('academyCatalog/c').deletedAt,null);const restored=await s.call('enroll',{courseId:'c'},'newLearner');assert.equal(restored.learnerId,'newLearner');});
test('AI-suggested answers block publishing until the author confirms them',()=>{const quiz=item('quiz','quiz');quiz.questions=[{...question('q'),aiSuggested:true}];let issues=domain.validateCourse(course([quiz]));assert.equal(issues.length,1);assert.equal(issues[0].code,'confirmAnswer');assert.equal(issues[0].questionId,'q');quiz.questions[0].aiSuggested=false;issues=domain.validateCourse(course([quiz]));assert.equal(issues.length,0);const pub=domain.publicCourse(course([{...quiz,aiDraft:true,questions:[{...question('q'),aiSuggested:true}]}]));assert.equal('aiDraft' in pub.items[0],false);assert.equal('aiSuggested' in pub.items[0].questions[0],false);});
